 # Computer Vision with Neural Networks

---

#### from Zero to Hero

In [4]:
import torch

## Understanding Tensors: The ABCs of PyTorch

In [6]:
tensor_1d = torch.tensor([1, 2, 3, 4, 5])
print('1D Tensor: \n', tensor_1d)

tensor_2d = torch.tensor([[1, 2], [3, 4]])
print('2D Tensor: \n', tensor_2d)

tensor_3d = torch.tensor([[[1, 2], [3, 4]],[[5, 6], [7, 8]]])
print('3D Tensor: \n', tensor_3d)

1D Tensor: 
 tensor([1, 2, 3, 4, 5])
2D Tensor: 
 tensor([[1, 2],
        [3, 4]])
3D Tensor: 
 tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


## Understanding Element-wise Operations

In [18]:
tensor_a = torch.tensor([1, 2, 3])
tensor_b = torch.tensor([4, 5, 6])

# Adding the tensors
added_tensor = tensor_a + tensor_b
print("Added Tensor: \n", added_tensor)

# Subtracting the tensors
subtracted_tensors = tensor_a - tensor_b
print("Subtracted Tensors: \n", subtracted_tensors)

# Multiplying the tensors
multiplied_tensor = tensor_a * tensor_b
print("Multiplied Tensor: \n", multiplied_tensor)

# Dividing the tensors
divided_tensors = tensor_a / tensor_b
print("Divided Tensors: \n", divided_tensors)


Added Tensor: 
 tensor([5, 7, 9])
Subtracted Tensors: 
 tensor([-3, -3, -3])
Multiplied Tensor: 
 tensor([ 4, 10, 18])
Divided Tensors: 
 tensor([0.2500, 0.4000, 0.5000])


• Tensor A: [1, 2, 3]
• Tensor B: [4, 5, 6]
When we add these tensors, PyTorch does this:
• 1 (from Tensor A) + 4 (from Tensor B) = 5
• 2 (from Tensor A) + 5 (from Tensor B) = 7
• 3 (from Tensor A) + 6 (from Tensor B) = 9
So, the result is a new tensor: [5, 7, 9]. Each element in this resulting tensor is
the sum of the corresponding elements from the two original tensors.

## Playing with Randomness: torch.rand

In [8]:
# Creating a tensor with random numbers
random_tensor = torch.rand(3, 3) # A 3*3 tensor
print("Random Tensor: \n", random_tensor)

Random Tensor: 
 tensor([[0.7672, 0.9908, 0.6795],
        [0.7022, 0.4510, 0.6356],
        [0.5258, 0.8275, 0.8153]])


Here, torch.rand(3, 3) creates a 3x3 tensor filled with random numbers between 0 and 1.

## Filling with Zeros: torch.zeros

In [9]:
# Creating a tensor filled with zeros
zeros_tensor = torch.zeros(2, 2)
print("Zeros Tensor: \n", zeros_tensor)

Zeros Tensor: 
 tensor([[0., 0.],
        [0., 0.]])


This command creates a 2x2 tensor where every number is 0

## Filling with Ones: torch.ones

Similarly, if we need a tensor where all elements are 1, we use torch.ones:

In [10]:
# Creating a tensor filled with ones
ones_tensor = torch.ones(2, 2)
print("Ones Tensor: \n", ones_tensor)

Ones Tensor: 
 tensor([[1., 1.],
        [1., 1.]])


## Changing Shapes: reshape and view

In [11]:
# Reshaping a tensor
original_tensor = torch.rand(4, 4)
print("Original Tensor: \n", original_tensor)

reshaped_tensor = original_tensor.reshape(2, 8)
print("Reshaped Tensor: \n", reshaped_tensor)

# Another way to reshape
viewed_tensor = original_tensor.view(2, 8)
print("Viewed Tensor: \n", viewed_tensor)

Original Tensor: 
 tensor([[0.6687, 0.8057, 0.6203, 0.1573],
        [0.6243, 0.6127, 0.9961, 0.7016],
        [0.6696, 0.5047, 0.3229, 0.1257],
        [0.6019, 0.4849, 0.4975, 0.2340]])
Reshaped Tensor: 
 tensor([[0.6687, 0.8057, 0.6203, 0.1573, 0.6243, 0.6127, 0.9961, 0.7016],
        [0.6696, 0.5047, 0.3229, 0.1257, 0.6019, 0.4849, 0.4975, 0.2340]])
Viewed Tensor: 
 tensor([[0.6687, 0.8057, 0.6203, 0.1573, 0.6243, 0.6127, 0.9961, 0.7016],
        [0.6696, 0.5047, 0.3229, 0.1257, 0.6019, 0.4849, 0.4975, 0.2340]])


Here, we start with a 4x4 tensor and reshape it into a 2x8 tensor. Both reshape 
and view do similar things, but they handle memory differently. It’s like choosing 
between different paths in a garden – the scenery changes, but the destination remains 
the same.


#### Understanding reshape
Think of reshape as rearranging the blocks on a spacious table. When you use
reshape, PyTorch checks if it needs to shuffle the blocks around to make the shape
you want. Sometimes, if the new shape is too different, PyTorch may decide to pick
up the blocks and rearrange them in a new order.


#### Understanding view
Now, view is a bit different. It’s like having the blocks on a fixed tray. When
you use view, PyTorch tries to just tilt or turn the tray to make the new shape,
without actually picking up and moving the blocks. This method is quicker but can
only be used if the new shape doesn’t require rearranging the blocks.

## Dot Product

DotProduct(A, B) = a1b1 + a2b2 + · · · + an ∗ bn

### Role in Machine Learning and Deep Learning.
• Calculating Weights: In neural networks, the dot product is used to calculate the weighted sum of inputs and weights. This is a fundamental aspect of
how information gets processed in neural networks.
• Measuring Similarity: The dot product is instrumental in algorithms that
measure the similarity between vectors, such as in cosine similarity where it
helps in determining the cosine of the angle between two vectors.
• Neural Network Computations: It is extensively used in the forward pass of a neural network to compute the activations of neurons

In [19]:
# Creating two 1D tensors (vectors)
vector_a = torch.tensor([1, 2, 3])
vector_b = torch.tensor([4, 5, 6])

# Calculating the dot product
dot_product = torch.dot(vector_a, vector_b)
print("Dot Product: \n", dot_product)

Dot Product: 
 tensor(32)
